### ISSUE TITLE
Refatorar código referente a mapa de valor captado

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#220]
### Description

Existe parte do código duplicada, e uma falta de coesão em certos componentes 

### Tasks

- [ ] Retirar duplicação de código de fetch (Mobile/Desktop)
- [ ] Deixar o componente do mapa de valor captado mais coeso e retirar código desnecessário de paginas como mapd2m1 e MapPage

### Acceptance Criteria

- [ ] Codigo coeso e desacoplado
- [ ] Dados e protótipos funcionam da mesma forma

**Comment by guilacerda** [comment]
- [ ] Refatorar o código do botão exportar CSV para ficar mais genérico e extensível

**Comment by guilacerda** [comment]
Com a entrega se aproximando e a ideia de dissolver o Promova nos outros dois projetos, foi priorizado outras issues para a finalização do Mapa de Valor Captado e não a refatoração do código (que ajudaria no desenvolvimento de novas visualizações). Porém, é importante a finalização da issue para um desenvolvimento futuro mais rápido e para ter um entendimento melhor do código. 

O PR #241 já iniciou esse trabalho.
