### ISSUE TITLE
Definir card para mapa de valor captado

### ISSUE THREAD

**Issue by joaaogui** [lappis-unb/PromovaCultura#224]
### Tasks

- [ ] Retirar a seta embaixo do card
- [ ] Redefinir espaço entre cursor e card
- [ ] Refinar visual do card
- [ ] ...

### Acceptance Criteria

- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...
