### ISSUE TITLE
Refatorar a função de aplicação de cores do heatmap

### ISSUE THREAD

**Issue by guilacerda** [lappis-unb/PromovaCultura#243]
### Descrição
Temos a necessidade de gerar as cores do mapa e do mobile (mapa) baseado nos valores que recebemos da api, dinamicamente. Existe a função referente à necessidade, porém não é reutilizável.

### Tasks

- [ ] Desvincular a função das cores do heatmap do mapa
- [ ] Analisar o modo como os parâmetros são recebidos
- [ ] Mudar o retorno da função das cores heatmap para uma forma genérica

### Critérios de Aceitação

- [ ] A função consegue ser utilizada tanto na versão desktop quanto para a mobile
