### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/PromovaCultura#4]
- [ ] Etapas do Projeto

- [ ] Proposta -- até -- prestação contas aprovadas

- [ ] Detalhamento/explicação de cada etapa

- [ ] INformações "automaticas" (SALIC)

- [ ] Valores à cada etapa

- [ ] Opções de visualização diferente (TL estilizada)

**Comment by joaaogui** [comment]
![timeline](https://user-images.githubusercontent.com/11447904/38503520-a894bd24-3be8-11e8-9b4a-90335f1a1197.jpg)

**Comment by joaaogui** [comment]
![timeline 2](https://user-images.githubusercontent.com/11447904/38503532-b57b7550-3be8-11e8-9522-f8989568657f.jpg)

**Comment by joaaogui** [comment]
![timeline 3](https://user-images.githubusercontent.com/11447904/38503546-bd5cb4a0-3be8-11e8-8eb7-180a6c4db766.jpg)

**Comment by joaaogui** [comment]
![timeline 4](https://user-images.githubusercontent.com/11447904/38503567-c8583668-3be8-11e8-81e5-86cf5762c4cb.jpg)

**Comment by rodmaia2099** [comment]
Mudanças no projeto tornaram essa issue dispensável
