### ISSUE TITLE
Indicadores culturais/sociais

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/PromovaCultura#5]
- [ ] Termômetro do valor

- [ ] Visualização Gráfica do impacto

- [ ] Gráficos de reações

**Comment by joaaogui** [comment]
![indicadores](https://user-images.githubusercontent.com/11447904/38503621-f357ae2a-3be8-11e8-9b83-60b3f0147ead.jpg)

**Comment by joaaogui** [comment]
![indicadores 2](https://user-images.githubusercontent.com/11447904/38503630-f9191c5e-3be8-11e8-9936-cfdc99fd8d15.jpg)

**Comment by joaaogui** [comment]
![indicadores 3](https://user-images.githubusercontent.com/11447904/38503636-fd9ec0a8-3be8-11e8-9314-fc71ce30af7b.jpg)

**Comment by rodmaia2099** [comment]
Fechando a issue por mudanças de direcionamento no projeto
